### ISSUE TITLE
Possible issue in "IonicDeploy.m" function "removeVersionFromPreferences

### ISSUE THREAD

**Issue by EyalSeagull** [driftyco/ionic-plugin-deploy#73] opened 2016-06-06 23:01 UTC
Hi,

First of all, thanks for an amazing service and a wonderful plugin.

I'm sorry if I'm not following the correct procedures to report a possible issue/correction, but I had some troubles with my app, and when I was debugging the **IonicDeploy.m** code in Xcode 7.3.1 I saw that the `removeVersionFromPreferences` might have an issue.

It looks like a missing formatting of the value in the `newVersions` variable (the `@"my_versions"` array excpect **NUMBER|UUID** format, not only the **UUID** part):

```
- (void) removeVersionFromPreferences:(NSString *) uuid {
    NSUserDefaults *prefs = [NSUserDefaults standardUserDefaults];
    NSArray *versions = [self getMyVersions];
    NSMutableArray *newVersions = [[NSMutableArray alloc] initWithCapacity:5];

    for (id version in versions) {
        NSArray *version_parts = [version componentsSeparatedByString:@"|"];
        NSString *version_uuid = version_parts[1];
        if (![version_uuid isEqualToString:uuid]) {
            [newVersions addObject:version_uuid];
        }
    }

    [prefs setObject:newVersions forKey:@"my_versions"];
    [prefs synchronize];
}
```

I don't program in Objectiv-C, but maybe changing the following line will do the trick:
`[newVersions addObject:version_uuid];`
To
`[newVersions addObject:version];`

It seems that in the "IonicDeploy.java" the problem does not exists. The code is already `newVersions.add(version);`

Hope it will help,

Eyal

**Comment by EyalSeagull** [comment] 2016-06-07 21:54
@Fuiste, in order to make things work, I had to manually remove **my_versions** and **version_count** from **NSUserDefaults** in the plugin init function.

Otherwise, **my_versions** will still have a non formatted value when the app starts (only **UUID** without the **NUMBER|UUID**) and the error persiste even changing the **removeVersionFromPreferences** function.

Maybe a check, when initializaing the plugin, to see if  **my_versions** values are valids will be necessary (and removing them if they aren't in valid format).

Again, hope these will help in anyway.

Eyal

**Comment by Fuiste** [comment] 2016-06-08 13:32
Hey guys, looking into this issue right now.  I'll post an update as soon as I reproduce the problem and publish an update if necessary.

**Comment by Fuiste** [comment] 2016-06-08 14:07
Ok, just made the change and tested it locally, looks like it's working well for me. (the fix is in `v0.5.6` of the plugin if you want to grab it).

Let me know if this solves things, and thanks for the heads up on the issue!

**Comment by EyalSeagull** [comment] 2016-06-09 13:44
Hi @Fuiste, v0.5.6 is working fine for me. Thanks for the rapid response.

**Comment by Fuiste** [comment] 2016-06-09 13:47
No problem, glad to help!

I'm going to close this issue for now, but tag me if there's problems down the road with this.

**Closed by Fuiste** 2016-06-09 13:47 UTC
