### ISSUE TITLE
cordova.js not loaded after $ionicDeploy.load() on iOS - only using UIWebView

### ISSUE THREAD

**Issue by falanso** [driftyco/ionic-plugin-deploy#124] opened 2017-05-07 07:58 UTC
I'm facing a problem, with $ionicDeploy.load() on iOS only,

on the first install if there is no update the app is working great.

whenever I apply an update using the ionic.io platform, and after the .load() is called. the app restart/refresh, and it load the first page and stops.

in the console, I got cordova.js?cacheBuster=xxxxxx not found on this server...

note that i DO have a in my index.html after the ng-cordova.js reference.

My solution for the moement was to stop the ionic deploy solution for the iOS but I need a fix.

btw: ionic plugin ls shows the ionic-deploy-plugin v0.6.6

**Comment by piotrowski** [comment] 2017-05-17 14:29
How are you using the plugin - ionic-cloud (Ionic v1) or ionic-cloud-angular (Ionic 2+)?
Can you show us how you do all the Deploy stuff?
Does cordova.js actually not exist after the update or is it just a temporary problem?
Does the problem fix itself if you kill and restart the app?
Does the app recover in any way or is it just broken afterwards?

**Comment by falanso** [comment] 2017-05-17 15:30
hello, 
sorry for not providing more info before.
i'm using ionic 1, with an old cli v2+ and node 4+ (environment  last updated ~1 year ago)
I tried to update all that, and it still didn't work. also the problem is now happening on android.
I update everything, my current setup is 
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.0.0

local packages:

    @ionic/cli-plugin-cordova : 1.0.0
    @ionic/cli-plugin-ionic1  : 1.0.0
    Ionic Framework           : ionic1 1.3.1

System:

    Node       : v7.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.8 

and still it's not working

Update code is the follow:
`$ionicPlatform.ready(function () {
        $scope.UpdateProgress = null;
        $ionicDeploy.channel = 'dev';
        $ionicDeploy.check().then(function (snapshotAvailable) {
            if (snapshotAvailable) {
                // When snapshotAvailable is true, you can apply the snapshot
                $scope.UpdateProgress = "Starting Download";
                $ionicDeploy.download({
                    onProgress: function (p) {
                        $timeout(function () {
                            $scope.UpdateProgress = "Downloading :" + p;
                        }, 200);
                    }
                }).then(
                    function () {
                        $ionicDeploy.extract({
                            onProgress: function (p) {
                                $timeout(function () {
                                    $scope.UpdateProgress = "Extracting :" + p;
                                }, 200);
                            }
                        }).then(
                            function () {
                                $ionicDeploy.load();
                            }, function () {
                                //failed
                                $scope.beforeRun();
                            });
                    }, function () {
                        //failed
                        $scope.beforeRun();
                    });
            } else {
                $scope.beforeRun();
            }
        });
    });`

if I close the app and open it again the problem persist. 
I noticed on android after the app refresh and is broken, if I click back it will go back to the previous splashscreen and work again, although after the closing and reopening the app it will stop working.

for me I fixed my situation by creating a total blank new project using the updated env.
on the first try, i copied my www folder to the new created project. but the problem came along and the new project also didn't work.
on the second try I created a new project again, I installed the plugins one by one using the cli, i installed on other dependencies using the bower and for app.js and index.html I copied the code manually line by line, I enable sass also manually in the new project. and the problem was solved.

my plugins list in the old project is:

com.clevertap.cordova.CleverTapPlugin 1.1.3 "CleverTap"
com.darktalker.cordova.screenshot 0.1.5 "Screenshot"
cordova-plugin-camera 2.3.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-crosswalk-webview 2.2.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-geolocation 2.4.1 "Geolocation"
cordova-plugin-inappbrowser 1.7.0 "InAppBrowser"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova.plugin.crop 0.0.1 "Crop"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-deploy 0.6.7 "IonicDeploy"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 6.0.4 "BarcodeScanner"

and the plugin in the latest project that is working currently is:
com.clevertap.cordova.CleverTapPlugin 1.2.1 "CleverTap"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-crosswalk-webview 2.3.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova.plugin.crop 0.0.1 "Crop"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-deploy 0.6.7 "IonicDeploy"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 6.0.6 "BarcodeScanner"

note that cordova.plugin.crop is a custom private paid plugin 
but the deploy was working while this plugin was installed.

btw, the problem started when I added the ios platform and I moved the project from windows to mac to build iOS. then when i commited the code back to windows it affected android and moved the problem to android too.

the weird thing now is if I compare the old and new www folders with a diff software, the differences are so minimal, and the difference is so minor. the angular version has a minor update, and ionic from 1.3.1 to 1.3.3

I think it would be good if I can discover the problem, just in case it happened in the future.

last note: I tried to remove ios and android and add the platforms again. but also it didn't work

sorry for the long comment

**Comment by piotrowski** [comment] 2017-05-17 15:36
Thanks for providing all that information.

I totally know these problems where something just doesn't work with Cordova, and then recreating the *identical* project it suddenly does. Most often it has to do with file permissions, some strange generated file or similar.

But the most important information was this:

> and the problem was solved.

So you are good now?

> I think it would be good if I can discover the problem, just in case it happened in the future.

I don't agree - you can waste hours or days just to find out you are not able to reproduce it at all. Something with the initial project was just borked. So if you are okay now, just close this issue here and if something similar happens in the future this one can still be found via Google or Github Search.

**Comment by falanso** [comment] 2017-05-17 15:43
thanks for the assistance.
yes now it is working, i'm fine now. 

I will close this now as you suggested and in case i had the time to investigate it I will re-comment it later here.

thanks, best

**Closed** 2017-05-17 22:23 UTC
