### ISSUE TITLE
update() function not work, nothing happen with the callback function.

### ISSUE THREAD

**Issue by ajenkul** [driftyco/ionic-plugin-deploy#33] opened 2015-09-21 03:35 UTC
Hi,
I have integrated success full the deploy plugin, it can check whether the new update is available or not.
But when I execute the update function to download the update, nothing was callback. I have tried to print out in the console but nothing return.
```javascript
$ionicDeploy.download().then(function() {
      // Extract the updates
      $ionicDeploy.extract().then(function() {
        // Load the updated version
        $ionicDeploy.load();
      }, function(error) {
        console.log("controllers.js:655 - ERROR EXTRACT");
        // Error extracting
      }, function(progress) {
        // Do something with the zip extraction progress
        console.log(progress);
      });
    }, function(error) {
      console.log("controllers.js:661 - ERROR DOWNLOAD UPDATE");
      // Error downloading the updates
    }, function(progress) {
      // Do something with the download progress
      console.log(progress);
    });
```
My app size is : ~200MB, is this plugin depend on the app size?
Because I've tried with simple app, it works fine.

**Comment by ericb** [comment] 2015-09-21 12:44
@ajenkul This might be a mismatch between your deploy plugin and service module. If you have the latest of both installed, try removing and adding the platform again.

**Comment by ajenkul** [comment] 2015-09-21 13:05
@ericb Thanks you. I'll give it a try and let you know later.

**Comment by ajenkul** [comment] 2015-09-22 15:30
@ericb I have tried it, in one same app. I deployed starter app first, then I copy all of my codes into that project, deploy again. If I set current app in https://apps.ionic.io/app/100faffe/deploy is the first deploy (starter), it works fine. But I change it to the new deploy, it won't work. I think it depend on the size of app. After copy all the database (~200mb) into `www` folder then upload it again it won't work anymore.

**Comment by afallou** [comment] 2015-09-23 18:33
I have the same thing happening, but only on iOS -just to be sure I did `ionic platform remove ios` and `ionic platform add ios`. My code is simply:
```
      $ionicDeploy.update().then(function(res) {
        $log.context('UpdateService.doUpdate').log('Ionic Deploy: Update Success! ', res);
      }, function(err) {
        $log.context('UpdateService.doUpdate').error('Ionic Deploy: Update error! ', err);
      }, function(prog) {
        $log.context('UpdateService.doUpdate').log('Ionic Deploy: Progress... ', prog);
      });
```
On Android I get the update progress correctly logged in the console, then the app restarts.
On iOS, I only get `Download complete (ionic-deploy.js:269)` logged to the console, then nothing.

**Comment by afallou** [comment] 2015-09-23 18:51
Ok, so to double-check  I also did `ionic platform remove android` and `ionic platform add android` and now both are broken. So now I have to figure out what changed there

**Comment by afallou** [comment] 2015-09-23 19:05
Just to be precise: here's the ouput for
`bower list`
```
beeyond#0.0.0 /Users/afallou/Code/beeyond
├─┬ angular-mocks#1.4.5 (1.4.6 available)
│ └── angular#1.4.5 (latest is 1.4.6)
├─┬ angular-sanitize#1.4.5 (1.4.6 available)
│ └── angular#1.4.5
├─┬ angular-ui-router#0.2.15
│ └── angular#1.4.5 (1.4.6 available)
├─┬ angularfire#1.1.2
│ ├── angular#1.4.5 (1.4.6 available)
│ └── firebase#2.2.9
├─┬ angulartics#0.19.3 (latest is 0.20.1)
│ ├── SHA-1#0.1.1
│ ├── angular#1.4.5 (1.4.6 available)
│ └── waypoints#3.1.1 (latest is 4.0.0)
├─┬ beeyond.firebase-auth#fe16e813ec extraneous
│ ├── angular#1.4.5 (1.4.6 available)
│ └─┬ angularfire#1.1.2
│   ├── angular#1.4.5
│   └── firebase#2.2.9
├─┬ ionic#1.0.1 (latest is 1.1.0)
│ ├── angular#1.4.5 incompatible with 1.3.13 (1.3.13 available, latest is 1.4.6)
│ ├─┬ angular-animate#1.3.13 (latest is 1.4.6)
│ │ └── angular#1.4.5
│ ├── angular-sanitize#1.4.5 incompatible with 1.3.13 (1.3.13 available, latest is 1.4.6)
│ └── angular-ui-router#0.2.15 incompatible with 0.2.13 (0.2.13 available, latest is 0.2.15)
├─┬ ionic-contrib-tinder-cards#723de6a935 extraneous
│ └── collide#1.0.0-beta.3 (latest is 0.0.4)
├─┬ ionic-ion-tinder-cards#f27713c6fe
│ └── collide#1.0.0-beta.3
├── ionic-service-core#0.1.10
├─┬ ionic-service-deploy#0.1.3
│ └── ionic-service-core#0.1.10
├─┬ ionic-service-push#0.1.13
│ └── ionic-service-core#0.1.10
├── mockfirebase#0.11.0
├── moment#2.10.6
├─┬ ngCordova#0.1.20-alpha (latest is null)
│ └── angular#1.4.5 (1.4.6 available)
├─┬ nouislider-angular#1.0.8 extraneous
│ ├── angular#1.4.5 incompatible with ~1.3.15 (1.3.19 available, latest is 1.4.6)
│ └─┬ nouislider#6.2.0 (latest is 8.0.2)
│   └── jquery#2.1.4
└── platform#1.3.0
```

And `cordova list`:
```
com.ionic.keyboard 1.0.4 "Keyboard"
com.phonegap.plugins.PushPlugin 2.5.0 "PushPlugin"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-inappbrowser 1.0.1 "InAppBrowser"
cordova-plugin-whitelist 1.1.0 "Whitelist"
ionic-plugin-deploy 0.3.0 "IonicDeploy"
org.apache.cordova.console 0.2.13 "Console"
```

**Comment by afallou** [comment] 2015-09-23 22:48
Got a bit further:
The plugin seems to work to some extent, since I get logs from it
In Android monitor, I get:
```
09-23 13:23:45.273: I/IONIC.DEPLOY.DOWNLOAD(28876): Downloading updates
09-23 13:23:45.274: I/IONIC.DEPLOY.HASVER(28876): Checking 5e1df5b8622311e5935ae6b1f39f4081...
09-23 13:23:45.274: I/IONIC.DEPLOY.HASVER(28876): c4ac0fd8621c11e5b91c2a971715771c == 5e1df5b8622311e5935ae6b1f39f4081
09-23 13:23:45.274: I/IONIC.DEPLOY.HASVER(28876): e635d212621f11e5aec486f6ef72b50c == 5e1df5b8622311e5935ae6b1f39f4081
09-23 13:23:45.274: I/IONIC.DEPLOY.HASVER(28876): 4c9dff78620911e5af5a7eafa35d7374 == 5e1df5b8622311e5935ae6b1f39f4081
09-23 13:23:45.274: I/IONIC.DEPLOY.HASVER(28876): 7bad35e6614511e5a17506c826a4d90c == 5e1df5b8622311e5935ae6b1f39f4081
09-23 13:23:45.274: I/IONIC.DEPLOY.HASVER(28876): No
```
And then no further log message from Ionic

**Comment by ajenkul** [comment] 2015-09-24 03:24
@ericb I've give it a try but it has same issue. I deleted all my sqlite file in `www` folder. So the app size reduce from 200mb to 10mb. Run `ionic upload` again and deploy it. It works fine. But with 200mb app size no more log message.
@afallou Did you try with sample app before?

**Comment by jakubrohleder** [comment] 2015-10-06 08:29
@afallou @ajenkul I have the same issue as you did, have you found a solution? Can you provide me with some help? (like packages versions or sample app)

I'm trying to make the sample ionic [deploy app work](http://docs.ionic.io/docs/deploy-from-scratch).

**Comment by benVigie** [comment] 2015-10-09 01:51
Same issue on my side. I switched to the new Ionic.io feature and now the deploy service doesn't work anymore on my ios `9.0.2` device.

I have traces from the ionic.io service for `check()` and `download()`, but as soon as I use `extract()` nothing happens. The *success*, *failure* and *progress* callback are never raised.

More of that, the app is broken after the `extract()` call. If I kill and launch again the app, files are corrupted and I have a beautiful, clean and clear white screen :smile:

**Comment by robksawyer** [comment] 2015-10-09 02:06
Getting the white screen of death on `9.0.2` as well. Here's what I see in the Xcode console log.
```
2015-10-08 17:59:31.529 MyApp[3246:939541] Apache Cordova native platform version 3.9.1 is starting.
2015-10-08 17:59:31.531 MyApp[3246:939541] Multi-tasking -> Device: YES, App: YES
2015-10-08 17:59:31.538 MyApp[3246:939541] Unlimited access to network resources
2015-10-08 17:59:31.669 MyApp[3246:939541] VERSION LABEL: 1.0.5:1444352350:
2015-10-08 17:59:31.669 MyApp[3246:939541] updating version label
2015-10-08 17:59:31.670 MyApp[3246:939541] [CDVTimer][ionicdeploy] 3.264964ms
2015-10-08 17:59:31.671 MyApp[3246:939541] [CDVTimer][keyboard] 0.738978ms
2015-10-08 17:59:31.705 MyApp[3246:939541] [CDVTimer][socialsharing] 33.933997ms
2015-10-08 17:59:31.733 MyApp[3246:939541] [CDVTimer][file] 27.764022ms
2015-10-08 17:59:31.733 MyApp[3246:939541] [CDVTimer][TotalPluginStartup] 66.519022ms
2015-10-08 17:59:31.745 MyApp[3246:939541] active
2015-10-08 17:59:31.953 MyApp[3246:939541] Resetting plugins due to page load.
2015-10-08 17:59:31.954 MyApp[3246:939541] uuid is: 
2015-10-08 17:59:31.954 MyApp[3246:939541] ignore deploy
2015-10-08 17:59:31.954 MyApp[3246:939541] ignore version: 
2015-10-08 17:59:33.504 MyApp[3246:939541] Finished load of: file:///var/mobile/Containers/Bundle/Application/2A224355-5074-4720-96AD-315557DB2EEF/MyApp.app/www/index.html#/app/landing
2015-10-08 17:59:33.956 MyApp[3246:939541] Push Plugin register called
2015-10-08 17:59:33.971 MyApp[3246:939541] Push Plugin register success: <3g754f8 46bdfcad cecca1c8 08de077e fd4e5d0b ecd719ba 2f4200d3 e9edb593>
2015-10-08 17:59:34.046 MyApp[3246:939541] Push Plugin register success: <3f7549f8 46bdfcad cecca1c8 08de077e fd4e5d0b ecd719ba 2f4200d3 e9edb593>
```

**Comment by abhinavgujjar** [comment] 2015-12-09 11:10
This was happening for me as well. I solved it by uploading the latest to ionic and deploying it. I think it was because ionic was not allowing rollback from a version that was unkown to it. Definitely a bug and spent a day figuring this out, but can only identify the symptom, not the cause

**Comment by Fuiste** [comment] 2016-09-02 15:50
Closing as this was an issue with the deprecated deploy libraries, and should be solved in the `ionic-cloud` client and latest version (`0.6.3`) of the deploy plugin.

**Closed by Fuiste** 2016-09-02 15:50 UTC
